version: "3.9"

services:
  seata-server:
    image: seataio/seata-server:latest
    container_name: seata-server
    env_file:
      - ./env/seata-server.env
    volumes:
      - ./volumes/seata-server/config:/root/seata-config
      - ./volumes/seata-server/logs:/root/logs
    ports:
      - "8091:8091"
    depends_on:
      - mysql
    restart: always
  mysql:
    image: mysql:5.7
    container_name: mysql-seata
    env_file:
      - ./env/mysql.env
    volumes:
      - ./volumes/mysql/data:/var/lib/mysql
      - ./volumes/mysql/conf:/etc/mysql
    ports:
      - "3307:3306"
    restart: always