version: "3.9"

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    container_name: elasticsearch
    env_file:
      - ./env/elasticsearch.env
    volumes:
      - ./volumes/elasticsearch/data:/usr/share/elasticsearch/data
      - ./volumes/elasticsearch/config:/usr/share/elasticsearch/config
      - ./volumes/elasticsearch/plugins:/usr/share/elasticsearch/plugins
      - ./volumes/elasticsearch/logs:/usr/share/elasticsearch/logs
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always
  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.3
    container_name: kibana
    depends_on:
     - es
    ports:
      - "5601:5601"
    restart: always
