version: "3.9"

services:
  nginx:
    image: nginx:1.21.6
    container_name: nginx
    volumes:
      - ./volumes/nginx/logs:/var/log/nginx
      - ./volumes/nginx/html:/usr/share/nginx/html
      - ./volumes/nginx/conf.d:/etc/nginx/conf.d
      - ./volumes/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    restart: always