version: "3.9"

services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos-standalone-mysql
    env_file:
      - ./env/nacos-standalone-mysql.env
    volumes:
      - ./volumes/nacos/standalone-logs/:/home/nacos/logs
      - ./volumes/nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    depends_on:
      - mysql
    restart: always
  mysql:
    image: nacos/nacos-mysql:8.0.16
    container_name: mysql-nacos-standalone
    env_file:
      - ./env/mysql.env
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always