version: "3.9"

services:
  redis:
    image: redis:6
    container_name: redis
    volumes:
      - ./volumes/redis/data:/data
      - ./volumes/redis/conf:/usr/local/etc/redis
    ports:
      - "6379:6379"
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always